# TCL File Generated by Component Editor 22.1
# Tue Sep 27 18:12:45 BST 2022
# DO NOT MODIFY


# 
# mkSerialLite3 "mkSerialLite3" v1.0
#  2022.09.27.18:12:45
# 
# 

# 
# request TCL package from ACDS 22.1
# 
package require -exact qsys 22.1


# 
# module mkSerialLite3
# 
set_module_property DESCRIPTION ""
set_module_property NAME mkSerialLite3
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME mkSerialLite3
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkSerialLite3_Instance
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mkSerialLite3_Instance.v VERILOG PATH bsv/output/mkSerialLite3_Instance.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point txstream
# 
add_interface txstream axi4stream end
set_interface_property txstream associatedClock clock_tx
set_interface_property txstream associatedReset reset_tx
set_interface_property txstream ENABLED true
set_interface_property txstream EXPORT_OF ""
set_interface_property txstream PORT_NAME_MAP ""
set_interface_property txstream CMSIS_SVD_VARIABLES ""
set_interface_property txstream SVD_ADDRESS_GROUP ""
set_interface_property txstream IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port txstream axs_txstream_tvalid tvalid Input 1
add_interface_port txstream axs_txstream_tdata tdata Input 256
add_interface_port txstream axs_txstream_tstrb tstrb Input 32
add_interface_port txstream axs_txstream_tkeep tkeep Input 32
add_interface_port txstream axs_txstream_tlast tlast Input 1
add_interface_port txstream axs_txstream_tuser tuser Input 9
add_interface_port txstream axs_txstream_tready tready Output 1


# 
# connection point rxstream
# 
add_interface rxstream axi4stream start
set_interface_property rxstream associatedClock clock_rx
set_interface_property rxstream associatedReset reset_rx
set_interface_property rxstream ENABLED true
set_interface_property rxstream EXPORT_OF ""
set_interface_property rxstream PORT_NAME_MAP ""
set_interface_property rxstream CMSIS_SVD_VARIABLES ""
set_interface_property rxstream SVD_ADDRESS_GROUP ""
set_interface_property rxstream IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rxstream axm_rxstream_tdata tdata Output 256
add_interface_port rxstream axm_rxstream_tstrb tstrb Output 32
add_interface_port rxstream axm_rxstream_tkeep tkeep Output 32
add_interface_port rxstream axm_rxstream_tlast tlast Output 1
add_interface_port rxstream axm_rxstream_tuser tuser Output 9
add_interface_port rxstream axm_rxstream_tvalid tvalid Output 1
add_interface_port rxstream axm_rxstream_tready tready Input 1


# 
# connection point conduit_end_0
# 
add_interface conduit_end_0 conduit end
set_interface_property conduit_end_0 associatedClock ""
set_interface_property conduit_end_0 associatedReset ""
set_interface_property conduit_end_0 ENABLED true
set_interface_property conduit_end_0 EXPORT_OF ""
set_interface_property conduit_end_0 PORT_NAME_MAP ""
set_interface_property conduit_end_0 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_0 SVD_ADDRESS_GROUP ""
set_interface_property conduit_end_0 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port conduit_end_0 coe_link_status export Output 11
add_interface_port conduit_end_0 coe_qsfp28_tx_pins export Output 4
add_interface_port conduit_end_0 coe_qsfp28_rx_pins_x export Input 4


# 
# connection point clock_tx
# 
add_interface clock_tx clock end
set_interface_property clock_tx ENABLED true
set_interface_property clock_tx EXPORT_OF ""
set_interface_property clock_tx PORT_NAME_MAP ""
set_interface_property clock_tx CMSIS_SVD_VARIABLES ""
set_interface_property clock_tx SVD_ADDRESS_GROUP ""
set_interface_property clock_tx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock_tx csi_tx_clk clk Input 1


# 
# connection point reset_tx
# 
add_interface reset_tx reset end
set_interface_property reset_tx associatedClock clock_tx
set_interface_property reset_tx synchronousEdges DEASSERT
set_interface_property reset_tx ENABLED true
set_interface_property reset_tx EXPORT_OF ""
set_interface_property reset_tx PORT_NAME_MAP ""
set_interface_property reset_tx CMSIS_SVD_VARIABLES ""
set_interface_property reset_tx SVD_ADDRESS_GROUP ""
set_interface_property reset_tx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset_tx rsi_tx_rst reset Input 1


# 
# connection point clock_rx
# 
add_interface clock_rx clock start
set_interface_property clock_rx associatedDirectClock ""
set_interface_property clock_rx ENABLED true
set_interface_property clock_rx EXPORT_OF ""
set_interface_property clock_rx PORT_NAME_MAP ""
set_interface_property clock_rx CMSIS_SVD_VARIABLES ""
set_interface_property clock_rx SVD_ADDRESS_GROUP ""
set_interface_property clock_rx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock_rx csi_cso_rx clk Output 1


# 
# connection point reset_rx
# 
add_interface reset_rx reset start
set_interface_property reset_rx associatedClock clock_tx
set_interface_property reset_rx associatedDirectReset ""
set_interface_property reset_rx associatedResetSinks ""
set_interface_property reset_rx synchronousEdges DEASSERT
set_interface_property reset_rx ENABLED true
set_interface_property reset_rx EXPORT_OF ""
set_interface_property reset_rx PORT_NAME_MAP ""
set_interface_property reset_rx CMSIS_SVD_VARIABLES ""
set_interface_property reset_rx SVD_ADDRESS_GROUP ""
set_interface_property reset_rx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset_rx rsi_rso_rx reset Output 1


# 
# connection point clock_axi4
# 
add_interface clock_axi4 clock end
set_interface_property clock_axi4 ENABLED true
set_interface_property clock_axi4 EXPORT_OF ""
set_interface_property clock_axi4 PORT_NAME_MAP ""
set_interface_property clock_axi4 CMSIS_SVD_VARIABLES ""
set_interface_property clock_axi4 SVD_ADDRESS_GROUP ""
set_interface_property clock_axi4 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock_axi4 csi clk Input 1


# 
# connection point reset_axi4
# 
add_interface reset_axi4 reset end
set_interface_property reset_axi4 associatedClock clock_tx
set_interface_property reset_axi4 synchronousEdges DEASSERT
set_interface_property reset_axi4 ENABLED true
set_interface_property reset_axi4 EXPORT_OF ""
set_interface_property reset_axi4 PORT_NAME_MAP ""
set_interface_property reset_axi4 CMSIS_SVD_VARIABLES ""
set_interface_property reset_axi4 SVD_ADDRESS_GROUP ""
set_interface_property reset_axi4 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset_axi4 rsi reset Input 1


# 
# connection point qsfp_refclk
# 
add_interface qsfp_refclk clock end
set_interface_property qsfp_refclk ENABLED true
set_interface_property qsfp_refclk EXPORT_OF ""
set_interface_property qsfp_refclk PORT_NAME_MAP ""
set_interface_property qsfp_refclk CMSIS_SVD_VARIABLES ""
set_interface_property qsfp_refclk SVD_ADDRESS_GROUP ""
set_interface_property qsfp_refclk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port qsfp_refclk csi_qsfp_refclk clk Input 1


# 
# connection point altera_axi4_slave_1
# 
add_interface altera_axi4_slave_1 axi4 end
set_interface_property altera_axi4_slave_1 associatedClock clock_axi4
set_interface_property altera_axi4_slave_1 associatedReset reset_axi4
set_interface_property altera_axi4_slave_1 readAcceptanceCapability 1
set_interface_property altera_axi4_slave_1 writeAcceptanceCapability 1
set_interface_property altera_axi4_slave_1 combinedAcceptanceCapability 1
set_interface_property altera_axi4_slave_1 readDataReorderingDepth 1
set_interface_property altera_axi4_slave_1 bridgesToMaster ""
set_interface_property altera_axi4_slave_1 ENABLED true
set_interface_property altera_axi4_slave_1 EXPORT_OF ""
set_interface_property altera_axi4_slave_1 PORT_NAME_MAP ""
set_interface_property altera_axi4_slave_1 CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4_slave_1 SVD_ADDRESS_GROUP ""
set_interface_property altera_axi4_slave_1 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port altera_axi4_slave_1 s_axi_management_awvalid awvalid Input 1
add_interface_port altera_axi4_slave_1 s_axi_management_awaddr awaddr Input 14
add_interface_port altera_axi4_slave_1 s_axi_management_awprot awprot Input 3
add_interface_port altera_axi4_slave_1 s_axi_management_awready awready Output 1
add_interface_port altera_axi4_slave_1 s_axi_management_wvalid wvalid Input 1
add_interface_port altera_axi4_slave_1 s_axi_management_wdata wdata Input 32
add_interface_port altera_axi4_slave_1 s_axi_management_wstrb wstrb Input 4
add_interface_port altera_axi4_slave_1 s_axi_management_wready wready Output 1
add_interface_port altera_axi4_slave_1 s_axi_management_bresp bresp Output 2
add_interface_port altera_axi4_slave_1 s_axi_management_bvalid bvalid Output 1
add_interface_port altera_axi4_slave_1 s_axi_management_bready bready Input 1
add_interface_port altera_axi4_slave_1 s_axi_management_arvalid arvalid Input 1
add_interface_port altera_axi4_slave_1 s_axi_management_araddr araddr Input 14
add_interface_port altera_axi4_slave_1 s_axi_management_arprot arprot Input 3
add_interface_port altera_axi4_slave_1 s_axi_management_arready arready Output 1
add_interface_port altera_axi4_slave_1 s_axi_management_rdata rdata Output 32
add_interface_port altera_axi4_slave_1 s_axi_management_rresp rresp Output 2
add_interface_port altera_axi4_slave_1 s_axi_management_rvalid rvalid Output 1
add_interface_port altera_axi4_slave_1 s_axi_management_rready rready Input 1

