# TCL File Generated by Component Editor 22.1
# Wed Feb 08 11:53:17 UTC 2023
# DO NOT MODIFY


# 
# mkSerialLite3_Instance "mkSerialLite3_Instance" v1.0
#  2023.02.08.11:53:17
# 
# 

# 
# request TCL package from ACDS 22.1
# 
package require -exact qsys 22.1


# 
# module mkSerialLite3_Instance
# 
set_module_property DESCRIPTION ""
set_module_property NAME mkSerialLite3_Instance
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME mkSerialLite3_Instance
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset mkSerialLite3_Instance_fileset QUARTUS_SYNTH "" ""
set_fileset_property mkSerialLite3_Instance_fileset TOP_LEVEL mkSerialLite3_Instance
set_fileset_property mkSerialLite3_Instance_fileset ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property mkSerialLite3_Instance_fileset ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file mkSerialLite3_Instance.v VERILOG PATH bsv/output/mkSerialLite3_Instance.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK_GATE_rx_clk
# 
add_interface CLK_GATE_rx_clk conduit end
set_interface_property CLK_GATE_rx_clk associatedClock csi_clk
set_interface_property CLK_GATE_rx_clk associatedReset rsi_rst_n
set_interface_property CLK_GATE_rx_clk ENABLED true
set_interface_property CLK_GATE_rx_clk EXPORT_OF ""
set_interface_property CLK_GATE_rx_clk PORT_NAME_MAP ""
set_interface_property CLK_GATE_rx_clk CMSIS_SVD_VARIABLES ""
set_interface_property CLK_GATE_rx_clk SVD_ADDRESS_GROUP ""
set_interface_property CLK_GATE_rx_clk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port CLK_GATE_rx_clk CLK_GATE_rx_clk CLK_GATE_rx_clk Output 1


# 
# connection point coe_link_status
# 
add_interface coe_link_status conduit end
set_interface_property coe_link_status associatedClock csi_clk
set_interface_property coe_link_status associatedReset rsi_rst_n
set_interface_property coe_link_status ENABLED true
set_interface_property coe_link_status EXPORT_OF ""
set_interface_property coe_link_status PORT_NAME_MAP ""
set_interface_property coe_link_status CMSIS_SVD_VARIABLES ""
set_interface_property coe_link_status SVD_ADDRESS_GROUP ""
set_interface_property coe_link_status IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port coe_link_status coe_link_status coe_link_status Output 15


# 
# connection point coe_qsfp28_rx_pins_x
# 
add_interface coe_qsfp28_rx_pins_x conduit end
set_interface_property coe_qsfp28_rx_pins_x associatedClock csi_clk
set_interface_property coe_qsfp28_rx_pins_x associatedReset rsi_rst_n
set_interface_property coe_qsfp28_rx_pins_x ENABLED true
set_interface_property coe_qsfp28_rx_pins_x EXPORT_OF ""
set_interface_property coe_qsfp28_rx_pins_x PORT_NAME_MAP ""
set_interface_property coe_qsfp28_rx_pins_x CMSIS_SVD_VARIABLES ""
set_interface_property coe_qsfp28_rx_pins_x SVD_ADDRESS_GROUP ""
set_interface_property coe_qsfp28_rx_pins_x IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port coe_qsfp28_rx_pins_x coe_qsfp28_rx_pins_x coe_qsfp28_rx_pins_x Input 4


# 
# connection point coe_qsfp28_tx_pins
# 
add_interface coe_qsfp28_tx_pins conduit end
set_interface_property coe_qsfp28_tx_pins associatedClock csi_clk
set_interface_property coe_qsfp28_tx_pins associatedReset rsi_rst_n
set_interface_property coe_qsfp28_tx_pins ENABLED true
set_interface_property coe_qsfp28_tx_pins EXPORT_OF ""
set_interface_property coe_qsfp28_tx_pins PORT_NAME_MAP ""
set_interface_property coe_qsfp28_tx_pins CMSIS_SVD_VARIABLES ""
set_interface_property coe_qsfp28_tx_pins SVD_ADDRESS_GROUP ""
set_interface_property coe_qsfp28_tx_pins IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port coe_qsfp28_tx_pins coe_qsfp28_tx_pins coe_qsfp28_tx_pins Output 4


# 
# connection point csi_clk
# 
add_interface csi_clk clock end
set_interface_property csi_clk ENABLED true
set_interface_property csi_clk EXPORT_OF ""
set_interface_property csi_clk PORT_NAME_MAP ""
set_interface_property csi_clk CMSIS_SVD_VARIABLES ""
set_interface_property csi_clk SVD_ADDRESS_GROUP ""
set_interface_property csi_clk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port csi_clk csi_clk clk Input 1


# 
# connection point csi_qsfp_refclk
# 
add_interface csi_qsfp_refclk clock end
set_interface_property csi_qsfp_refclk ENABLED true
set_interface_property csi_qsfp_refclk EXPORT_OF ""
set_interface_property csi_qsfp_refclk PORT_NAME_MAP ""
set_interface_property csi_qsfp_refclk CMSIS_SVD_VARIABLES ""
set_interface_property csi_qsfp_refclk SVD_ADDRESS_GROUP ""
set_interface_property csi_qsfp_refclk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port csi_qsfp_refclk csi_qsfp_refclk clk Input 1


# 
# connection point csi_tx_clk
# 
add_interface csi_tx_clk clock end
set_interface_property csi_tx_clk ENABLED true
set_interface_property csi_tx_clk EXPORT_OF ""
set_interface_property csi_tx_clk PORT_NAME_MAP ""
set_interface_property csi_tx_clk CMSIS_SVD_VARIABLES ""
set_interface_property csi_tx_clk SVD_ADDRESS_GROUP ""
set_interface_property csi_tx_clk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port csi_tx_clk csi_tx_clk clk Input 1


# 
# connection point cso_rx_clk
# 
add_interface cso_rx_clk clock start
set_interface_property cso_rx_clk associatedDirectClock ""
set_interface_property cso_rx_clk ENABLED true
set_interface_property cso_rx_clk EXPORT_OF ""
set_interface_property cso_rx_clk PORT_NAME_MAP ""
set_interface_property cso_rx_clk CMSIS_SVD_VARIABLES ""
set_interface_property cso_rx_clk SVD_ADDRESS_GROUP ""
set_interface_property cso_rx_clk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port cso_rx_clk cso_rx_clk clk Output 1


# 
# connection point management
# 
add_interface management axi4lite end
set_interface_property management associatedClock csi_clk
set_interface_property management associatedReset rsi_rst_n
set_interface_property management readAcceptanceCapability 1
set_interface_property management writeAcceptanceCapability 1
set_interface_property management combinedAcceptanceCapability 1
set_interface_property management bridgesToMaster ""
set_interface_property management ENABLED true
set_interface_property management EXPORT_OF ""
set_interface_property management PORT_NAME_MAP ""
set_interface_property management CMSIS_SVD_VARIABLES ""
set_interface_property management SVD_ADDRESS_GROUP ""
set_interface_property management IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port management axls_management_rready rready Input 1
add_interface_port management axls_management_rvalid rvalid Output 1
add_interface_port management axls_management_rresp rresp Output 2
add_interface_port management axls_management_rdata rdata Output 32
add_interface_port management axls_management_arready arready Output 1
add_interface_port management axls_management_arprot arprot Input 3
add_interface_port management axls_management_araddr araddr Input 16
add_interface_port management axls_management_arvalid arvalid Input 1
add_interface_port management axls_management_bready bready Input 1
add_interface_port management axls_management_bvalid bvalid Output 1
add_interface_port management axls_management_bresp bresp Output 2
add_interface_port management axls_management_wready wready Output 1
add_interface_port management axls_management_wstrb wstrb Input 4
add_interface_port management axls_management_wdata wdata Input 32
add_interface_port management axls_management_wvalid wvalid Input 1
add_interface_port management axls_management_awready awready Output 1
add_interface_port management axls_management_awprot awprot Input 3
add_interface_port management axls_management_awaddr awaddr Input 16
add_interface_port management axls_management_awvalid awvalid Input 1


# 
# connection point rsi_rst_n
# 
add_interface rsi_rst_n reset end
set_interface_property rsi_rst_n associatedClock csi_clk
set_interface_property rsi_rst_n synchronousEdges DEASSERT
set_interface_property rsi_rst_n ENABLED true
set_interface_property rsi_rst_n EXPORT_OF ""
set_interface_property rsi_rst_n PORT_NAME_MAP ""
set_interface_property rsi_rst_n CMSIS_SVD_VARIABLES ""
set_interface_property rsi_rst_n SVD_ADDRESS_GROUP ""
set_interface_property rsi_rst_n IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rsi_rst_n rsi_rst_n reset_n Input 1


# 
# connection point rsi_tx_rst_n
# 
add_interface rsi_tx_rst_n reset end
set_interface_property rsi_tx_rst_n associatedClock csi_tx_clk
set_interface_property rsi_tx_rst_n synchronousEdges DEASSERT
set_interface_property rsi_tx_rst_n ENABLED true
set_interface_property rsi_tx_rst_n EXPORT_OF ""
set_interface_property rsi_tx_rst_n PORT_NAME_MAP ""
set_interface_property rsi_tx_rst_n CMSIS_SVD_VARIABLES ""
set_interface_property rsi_tx_rst_n SVD_ADDRESS_GROUP ""
set_interface_property rsi_tx_rst_n IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rsi_tx_rst_n rsi_tx_rst_n reset_n Input 1


# 
# connection point rso_rx_rst_n
# 
add_interface rso_rx_rst_n reset start
set_interface_property rso_rx_rst_n associatedClock cso_rx_clk
set_interface_property rso_rx_rst_n associatedDirectReset ""
set_interface_property rso_rx_rst_n associatedResetSinks ""
set_interface_property rso_rx_rst_n synchronousEdges DEASSERT
set_interface_property rso_rx_rst_n ENABLED true
set_interface_property rso_rx_rst_n EXPORT_OF ""
set_interface_property rso_rx_rst_n PORT_NAME_MAP ""
set_interface_property rso_rx_rst_n CMSIS_SVD_VARIABLES ""
set_interface_property rso_rx_rst_n SVD_ADDRESS_GROUP ""
set_interface_property rso_rx_rst_n IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rso_rx_rst_n rso_rx_rst_n reset_n Output 1


# 
# connection point rx
# 
add_interface rx axi4stream start
set_interface_property rx associatedClock cso_rx_clk
set_interface_property rx associatedReset rso_rx_rst_n
set_interface_property rx ENABLED true
set_interface_property rx EXPORT_OF ""
set_interface_property rx PORT_NAME_MAP ""
set_interface_property rx CMSIS_SVD_VARIABLES ""
set_interface_property rx SVD_ADDRESS_GROUP ""
set_interface_property rx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx axstrm_rx_tready tready Input 1
add_interface_port rx axstrm_rx_tvalid tvalid Output 1
add_interface_port rx axstrm_rx_tuser tuser Output 9
add_interface_port rx axstrm_rx_tlast tlast Output 1
add_interface_port rx axstrm_rx_tkeep tkeep Output 32
add_interface_port rx axstrm_rx_tstrb tstrb Output 32
add_interface_port rx axstrm_rx_tdata tdata Output 256


# 
# connection point tx
# 
add_interface tx axi4stream end
set_interface_property tx associatedClock csi_tx_clk
set_interface_property tx associatedReset rsi_tx_rst_n
set_interface_property tx ENABLED true
set_interface_property tx EXPORT_OF ""
set_interface_property tx PORT_NAME_MAP ""
set_interface_property tx CMSIS_SVD_VARIABLES ""
set_interface_property tx SVD_ADDRESS_GROUP ""
set_interface_property tx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx axstrs_tx_tready tready Output 1
add_interface_port tx axstrs_tx_tuser tuser Input 9
add_interface_port tx axstrs_tx_tlast tlast Input 1
add_interface_port tx axstrs_tx_tkeep tkeep Input 32
add_interface_port tx axstrs_tx_tstrb tstrb Input 32
add_interface_port tx axstrs_tx_tdata tdata Input 256
add_interface_port tx axstrs_tx_tvalid tvalid Input 1

