# TCL File Generated by Component Editor 22.1
# Fri Jan 20 11:40:05 UTC 2023
# DO NOT MODIFY


# 
# mkStatusDevice_Instance "mkStatusDevice_Instance" v1.0
#  2023.01.20.11:40:05
# 
# 

# 
# request TCL package from ACDS 22.1
# 
package require -exact qsys 22.1


# 
# module mkStatusDevice_Instance
# 
set_module_property DESCRIPTION ""
set_module_property NAME mkStatusDevice_Instance
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME mkStatusDevice_Instance
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset mkStatusDevice_Instance_fileset QUARTUS_SYNTH "" ""
set_fileset_property mkStatusDevice_Instance_fileset TOP_LEVEL mkStatusDevice_Instance
set_fileset_property mkStatusDevice_Instance_fileset ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property mkStatusDevice_Instance_fileset ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file mkStatusDevice_Instance.v VERILOG PATH S10FPGA/output/mkStatusDevice_Instance.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""
set_interface_property CLK IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RST_N
# 
add_interface RST_N reset end
set_interface_property RST_N associatedClock CLK
set_interface_property RST_N synchronousEdges DEASSERT
set_interface_property RST_N ENABLED true
set_interface_property RST_N EXPORT_OF ""
set_interface_property RST_N PORT_NAME_MAP ""
set_interface_property RST_N CMSIS_SVD_VARIABLES ""
set_interface_property RST_N SVD_ADDRESS_GROUP ""
set_interface_property RST_N IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port RST_N RST_N reset_n Input 1


# 
# connection point coe_status_a_coe
# 
add_interface coe_status_a_coe conduit end
set_interface_property coe_status_a_coe associatedClock ""
set_interface_property coe_status_a_coe associatedReset ""
set_interface_property coe_status_a_coe ENABLED true
set_interface_property coe_status_a_coe EXPORT_OF ""
set_interface_property coe_status_a_coe PORT_NAME_MAP ""
set_interface_property coe_status_a_coe CMSIS_SVD_VARIABLES ""
set_interface_property coe_status_a_coe SVD_ADDRESS_GROUP ""
set_interface_property coe_status_a_coe IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port coe_status_a_coe coe_status_a_coe coe_status_a_coe Input 32


# 
# connection point coe_status_b_coe
# 
add_interface coe_status_b_coe conduit end
set_interface_property coe_status_b_coe associatedClock ""
set_interface_property coe_status_b_coe associatedReset ""
set_interface_property coe_status_b_coe ENABLED true
set_interface_property coe_status_b_coe EXPORT_OF ""
set_interface_property coe_status_b_coe PORT_NAME_MAP ""
set_interface_property coe_status_b_coe CMSIS_SVD_VARIABLES ""
set_interface_property coe_status_b_coe SVD_ADDRESS_GROUP ""
set_interface_property coe_status_b_coe IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port coe_status_b_coe coe_status_b_coe coe_status_b_coe Input 32


# 
# connection point coe_status_c_coe
# 
add_interface coe_status_c_coe conduit end
set_interface_property coe_status_c_coe associatedClock ""
set_interface_property coe_status_c_coe associatedReset ""
set_interface_property coe_status_c_coe ENABLED true
set_interface_property coe_status_c_coe EXPORT_OF ""
set_interface_property coe_status_c_coe PORT_NAME_MAP ""
set_interface_property coe_status_c_coe CMSIS_SVD_VARIABLES ""
set_interface_property coe_status_c_coe SVD_ADDRESS_GROUP ""
set_interface_property coe_status_c_coe IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port coe_status_c_coe coe_status_c_coe coe_status_c_coe Input 32


# 
# connection point coe_status_d_coe
# 
add_interface coe_status_d_coe conduit end
set_interface_property coe_status_d_coe associatedClock ""
set_interface_property coe_status_d_coe associatedReset ""
set_interface_property coe_status_d_coe ENABLED true
set_interface_property coe_status_d_coe EXPORT_OF ""
set_interface_property coe_status_d_coe PORT_NAME_MAP ""
set_interface_property coe_status_d_coe CMSIS_SVD_VARIABLES ""
set_interface_property coe_status_d_coe SVD_ADDRESS_GROUP ""
set_interface_property coe_status_d_coe IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port coe_status_d_coe coe_status_d_coe coe_status_d_coe Input 32


# 
# connection point mem_csrs
# 
add_interface mem_csrs axi4lite end
set_interface_property mem_csrs associatedClock CLK
set_interface_property mem_csrs associatedReset RST_N
set_interface_property mem_csrs readAcceptanceCapability 1
set_interface_property mem_csrs writeAcceptanceCapability 1
set_interface_property mem_csrs combinedAcceptanceCapability 1
set_interface_property mem_csrs bridgesToMaster ""
set_interface_property mem_csrs ENABLED true
set_interface_property mem_csrs EXPORT_OF ""
set_interface_property mem_csrs PORT_NAME_MAP ""
set_interface_property mem_csrs CMSIS_SVD_VARIABLES ""
set_interface_property mem_csrs SVD_ADDRESS_GROUP ""
set_interface_property mem_csrs IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port mem_csrs axls_mem_csrs_rready rready Input 1
add_interface_port mem_csrs axls_mem_csrs_rvalid rvalid Output 1
add_interface_port mem_csrs axls_mem_csrs_rresp rresp Output 2
add_interface_port mem_csrs axls_mem_csrs_rdata rdata Output 32
add_interface_port mem_csrs axls_mem_csrs_arready arready Output 1
add_interface_port mem_csrs axls_mem_csrs_arprot arprot Input 3
add_interface_port mem_csrs axls_mem_csrs_araddr araddr Input 5
add_interface_port mem_csrs axls_mem_csrs_arvalid arvalid Input 1
add_interface_port mem_csrs axls_mem_csrs_bready bready Input 1
add_interface_port mem_csrs axls_mem_csrs_bvalid bvalid Output 1
add_interface_port mem_csrs axls_mem_csrs_bresp bresp Output 2
add_interface_port mem_csrs axls_mem_csrs_wready wready Output 1
add_interface_port mem_csrs axls_mem_csrs_wstrb wstrb Input 4
add_interface_port mem_csrs axls_mem_csrs_wdata wdata Input 32
add_interface_port mem_csrs axls_mem_csrs_wvalid wvalid Input 1
add_interface_port mem_csrs axls_mem_csrs_awready awready Output 1
add_interface_port mem_csrs axls_mem_csrs_awprot awprot Input 3
add_interface_port mem_csrs axls_mem_csrs_awaddr awaddr Input 5
add_interface_port mem_csrs axls_mem_csrs_awvalid awvalid Input 1

